### ISSUE TITLE
[Docker] How to run capture on Ubuntu

### ISSUE THREAD

**Issue by evacfk** [denverquane/automuteus#104]
Hi, thanks for creating this great tool.

I'm hosting this on Ubuntu via docker-compose. The discord portion is running fine, i created a host.txt file in the same folder as my docker-compose.yml (does it matter where this is?). In the host.txt file i entered ip:defaultport. 

The only part where i'm puzzled is how do I run the capture remotely?

I cloned the capture repo and ran installer.py and it results in:

`Traceback (most recent call last):
  File "installer.py", line 110, in <module>
    master1 = tk.Tk()
  File "/usr/lib/python3.6/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable`

**Comment by abdellahaski** [comment]
As far as I know the capture can't run remotely you're supposed to run it locally with the game

**Comment by denverquane** [comment]
Yes, that is correct. There is no way to run the capture remotely, it relies on the game running on the same pc to... well, capture the game state. Among Us has no formal API that would allow the capture to run remotely.

@evacfk What capture repo are you talking about? we have no python code in the capture repo...
https://github.com/denverquane/amonguscapture

**Comment by Greenpilot4** [comment]
@evacfk how did you mange to get this running on Ubuntu? Mine just keeps giving me "exec format error"

**Comment by TauAkiou** [comment]
If you're interesting in running the capture on Linux, use my fork:

https://github.com/TauAkiou/amonguscapture-gtk

This is a GTK rework of the capture with a reworked Linux memory backend. It builds into a native Linux executable and, as far as my testing has gone, works fairly effectively.

**Comment by jasikpark** [comment]
https://github.com/TauAkiou/amonguscapture-gtk/issues/3 I finally got capture to run on Ubuntu with amonguscapture-gtk + setting ptrace permisisons for the binary with setcomp
