### ISSUE TITLE
[Feature Request] Multi Game Support

### ISSUE THREAD

**Issue by ThinkingParadox** [denverquane/automuteus#143]
Would it be possible to do multi game support that tracks multiple games with multiple voice chat rooms? This would be nice to have in case you want to run multiple games at once. Every time I try to use the new game command at the moment it just overwrites the old game. # #

**Comment by denverquane** [comment]
We're limited by the discord api (it limits API requests by discord server, not by voice channel): check the faq on our Discord server. But with 2+ discord bot tokens, it would probably be more viable, I'll look into it

**Comment by ThinkingParadox** [comment]
Yah that's probably the easiest way to do it. Maybe having the bots take care of a channel each. That might be easier to manage as well as more stable. Not sure how easy it would do if you wanted to make a public instance of the bot though. Still would be nice for private instances.

**Comment by denverquane** [comment]
Has been added in v4.0+ :)
