### ISSUE TITLE
[Feature Request] Freeze command & voice channel system

### ISSUE THREAD

**Issue by Keyboardsheep** [denverquane/automuteus#153]
The two features I think would be nice are:

1. A freeze command which prevents people from unlinking or changing what color they are linked to. This would prevent dead people from selecting a living person and talking to alive people. (There would also be an unfreeze command)
2. A setting in the config where you can choose to use multiple voice channels so that when someone dies they are moved to the dead voice channel so that they can talk the entire time. Roles would make it so that people can't join the wrong channel.

**Comment by denverquane** [comment]
The "freeze" command has been added as `.au pause`, but I don't think we'll explore the option of moving players around; we already have problems with the Discord rate-limits, and there are other bots linked in our readme that can accomplish this kind of functionality instead
