### ISSUE TITLE
Feature request: Send the message with new code on lobbyUpdate for phone users (with code)

### ISSUE THREAD

**Issue by Snow4DV** [denverquane/automuteus#157]
Users playing on phone are not able to copy the code from discord message (can only copy the whole message) and sometimes i have to teach new players where they can get the code so it would be cool to add feature that 'd send it as a plain message to the main text channel with exact name. Here's my code with hardcored text channel name: 

`case lobbyUpdate := <-*lobbyUpdates:
				if guild, ok := bot.AllGuilds[lobbyUpdate.GuildID]; ok {
					guild.Linked = true
					guild.AmongUsData.SetRoomRegion(lobbyUpdate.Lobby.LobbyCode, lobbyUpdate.Lobby.Region.ToString()) // Set new room code
					//sendind plain code to the channel that is not the one where is bot
					for _, guild := range dg.State.Guilds {
						// Get channels for this guild
						channels, _ := dg.GuildChannels(guild.ID)
						for _, c := range channels {
							// Check if channel is a guild text channel and not a voice or DM channel
							if c.Type != discordgo.ChannelTypeGuildText {
								continue
							}
							//Check if name is the one i want
							if c.Name != "основной" {
								continue
							}
							// Send text messages
							dg.ChannelMessageSend(
								c.ID,
								"Host joined a lobby in region \"" + lobbyUpdate.Lobby.Region.ToString() + "\":",
							)
							dg.ChannelMessageSend(
								c.ID,
								lobbyUpdate.Lobby.LobbyCode,
							)
						}
					}
					guild.GameStateMsg.Edit(dg, gameStateResponse(guild))                                             // Update game state message
				}
			}`

**Comment by denverquane** [comment]
Should be addressed in the latest versions
