### ISSUE TITLE
Bot visual Giveaway

### ISSUE THREAD

**Issue by SecsiGaming** [denverquane/automuteus#179]
1 of my friends noticed last night when a player is killed it updates the players picture on the bot as soon as they are killed. This leads to the chance of people watching the bot as "vitals". Would recommend to only update character status once a body is found or meeting button is pressed.

**Comment by denverquane** [comment]
This definitely shouldn't happen under normal circumstances. Is your "unmuteDeadPlayersTasks" (I can't remember the precise name of the setting) enabled? Is anyone typing `.au refresh` to regenerate the message? Under normal circumstances, the bot should never update the status message when a player dies

**Comment by xTCry** [comment]
Everything works stably.
The Emoji of the killed player appears only when the voting starts

**Comment by rorosaurus** [comment]
I experienced this today with the latest of discord/capture programs.

DarkWight died and his body icon was immediately updated to dead on discord.
Mr Meme died shortly after, and his body icon was not updated until the next meeting. (as expected)

My conclusion is there is some bug here. :)

relevant log:
````
[ClientSocket]: Room code (FFAQWQ) sent to server.
[PlayerChange]: Tasty: Joined
[PlayerChange]: Cerb: Joined
[PlayerChange]: Anthy: Joined
[PlayerChange]: Klingo: Joined
[PlayerChange]: DarkWight: Joined
[PlayerChange]: not sus: Joined
[GameMemReader]: State changed to TASKS
[PlayerChange]: DarkWight: Died
[PlayerChange]: Klingo: Disconnected
[PlayerChange]: Mr Meme: Died
[GameMemReader]: State changed to DISCUSSION
[GameMemReader]: State changed to TASKS
[GameMemReader]: State changed to DISCUSSION
[GameMemReader]: State changed to TASKS
[GameMemReader]: State changed to LOBBY
````

**Comment by denverquane** [comment]
I'd probably need the Bot logs to assist with this; the capture always sends *all* events (to be an accurate source of truth), whereas the bot is responsible for filtering down what messages should update the status. I might just have the status message be never updated during the tasks phase (although this isn't good for users that join/link late, as they won't get feedback...), but it would prevent this rare issue

**Comment by denverquane** [comment]
From those logs, @rorosaurus , my guess is that Klingo disconnecting is what caused the status message to be updated. It should update to give the feedback that a player isn't detected anymore, but in this case it did cause the message to be updated

**Comment by rorosaurus** [comment]
Yeah sorry, I glanced over the discord bot logs and couldn't tell which portion of the logs represented this same portion of capture log. :S I think I've found it now though:

````
2020/10/23 18:04:47 Detected transition to Tasks
2020/10/23 18:04:47 Sleeping for 2 seconds before applying changes to users
2020/10/23 18:04:50 Issuing update request to discord for userID 181592072023703552 with mute=true deaf=true
2020/10/23 18:04:50 Issuing update request to discord for userID 472063749553913856 with mute=true deaf=true
2020/10/23 18:04:50 Issuing update request to discord for userID 174970669786726400 with mute=true deaf=true
2020/10/23 18:04:50 Issuing update request to discord for userID 342927385919881226 with mute=true deaf=true
2020/10/23 18:04:50 Issuing update request to discord for userID 362450818634612736 with mute=true deaf=true
2020/10/23 18:04:50 Issuing update request to discord for userID 193197936585211904 with mute=true deaf=true
2020/10/23 18:04:50 Issuing update request to discord for userID 292856997592694784 with mute=true deaf=true
2020/10/23 18:04:51 Issuing update request to discord for userID 342927385919881226 with mute=true deaf=true
2020/10/23 18:04:51 Issuing update request to discord for userID 362450818634612736 with mute=true deaf=true
2020/10/23 18:05:28 player received from capture:  {"Action":2,"Name":"DarkWight","IsDead":true,"Disconnected":false,"Color":1}
2020/10/23 18:05:28 Received PlayerUpdate message for guild 757816758894854164
2020/10/23 18:05:28 Updated { Name: DarkWight, Color: blue, Alive: false }
2020/10/23 18:05:28 Attempting to link via cached user names
2020/10/23 18:05:28 Paired 174970669786726400 to their cached name of DarkWight!
2020/10/23 18:05:28 NOT updating the discord status message; would leak info
2020/10/23 18:05:28 Bot inactivity timer has been reset to 3600 seconds
2020/10/23 18:06:00 player received from capture:  {"Action":5,"Name":"Klingo","IsDead":false,"Disconnected":true,"Color":0}
2020/10/23 18:06:00 Bot inactivity timer has been reset to 3600 seconds
2020/10/23 18:06:00 Received PlayerUpdate message for guild 757816758894854164
2020/10/23 18:06:00 I detected that Klingo disconnected or left! I'm removing their linked game data; they will need to relink
2020/10/23 18:06:22 player received from capture:  {"Action":2,"Name":"Mr Meme","IsDead":true,"Disconnected":false,"Color":3}
2020/10/23 18:06:22 Bot inactivity timer has been reset to 3600 seconds
2020/10/23 18:06:22 Received PlayerUpdate message for guild 757816758894854164
2020/10/23 18:06:22 Updated { Name: Mr Meme, Color: pink, Alive: false }
2020/10/23 18:06:22 Attempting to link via cached user names
2020/10/23 18:06:22 Paired 181592072023703552 to their cached name of Mr Meme!
2020/10/23 18:06:22 NOT updating the discord status message; would leak info
2020/10/23 18:06:50 phase received from capture:  2
2020/10/23 18:06:50 Pushing phase event to channel
2020/10/23 18:06:50 Bot inactivity timer has been reset to 3600 seconds
2020/10/23 18:06:50 Received PhaseUpdate message for guild 757816758894854164
2020/10/23 18:06:50 Detected transition to Discussion
````

Your guess sounds like a good point. That could explain why this bug doesn't easily reproduce.

**Comment by bin101** [comment]
@denverquane You are right. In case of a player disconnect the Message gets updated:
https://github.com/denverquane/automuteus/blob/04d64e672e99dc6a775cc1d4c621e580c99d1259/discord/bot.go#L647-L653

**Comment by denverquane** [comment]
This has been fixed/addressed in the latest versions of the bot, I believe v4.0+ :)
