### ISSUE TITLE
[Issue] Discord members being unable to hear/speak to anyone 

### ISSUE THREAD

**Issue by Easyidle123** [denverquane/automuteus#181]
This happens to both alive and dead players at random intervals. One person will be unable to hear or speak to anyone else, despite still being in the call, not being server muted/deafened, and not being muted or deafened on their own. Dragging them out of the call and back in manually seems to fix it. Is this a known issue with discord, or with the bot?

I'm using the discordbot release version 2.3.4_windows_32bit. My operating system is 64 bit. I'm using the capture release version 2.4.1.
The discord bot was created on an older version, and the folder's executables have been simply deleted and replaced with their updated versions as new versions have come out, however it's seemed to function perfectly normally other than this bug. I had an isolated incident of the bot not updating for anyone, and requiring the capture and bot's windows to be closed before it would resume, but I'm assuming it was unrelated.

**Comment by Gabgaouette** [comment]
I had the same issue today with the 2.3.4
People need to leave and come back

**Comment by denverquane** [comment]
Pretty sure it's an issue with discord. If the users don't show up as muted or deafened in the Discord UI, then it really can't be anything else but a Discord-facing problem
