### ISSUE TITLE
Admins do not work

### ISSUE THREAD

**Issue by beheh** [denverquane/automuteus#183]
On the latest master, setting admins will lock anyone but the guild owner out and permission roles.

This is due to a bug in `HasAdminPerms` that tries to access `Message.Member.User`, which is not set as per [Discord GuildMember docs](https://discord.com/developers/docs/resources/guild#guild-member-object):

> The field user `user` won't be included in the member object attached to `MESSAGE_CREATE` and `MESSAGE_UPDATE` gateway events.

A fix might be to replace the member param with a user object or the user id directly.

Note that in order to reproduce this you must be in a server you don't own, as there is a hard bypass that ensures the guild/server owner always has access.

**Comment by denverquane** [comment]
Thanks for filing the issue (and one of the fixes!). I merged in a change that addresses it by using the m.Author instead of m.Member.User, so hopefully this is fixed now. Thanks for providing the extensive detail on your PR, btw :)
