### ISSUE TITLE
[user settings] :  improve config

### ISSUE THREAD

**Issue by fradali** [denverquane/automuteus#185]
Hi,

Thanks for the hard work, I have a little advice , I saw that every time a player join a config file is generated to this user, the format is like this :
```
{
    "userID": "xxxxxx",
    "username": "xxxxx",
    "gameNames": [
        "xxxxx"
    ]
}
```
So what I sugg if possible is read one file --> loop (for each)  so the structure goes like this :  [{}, {} , {} ...] array of objects.

Use the userID to find out if this user exists or not , if not add it with gameNames if not check if gameName is diffirent from the current one , if is diff --> do update

that's will let you create only one file for all users.

hope that clear , I'm not familiar with Go but if you want a help with the algorithm I can do it ! :) 

Cheers

**Comment by denverquane** [comment]
Appreciate the suggestion. The file storage is very much a temporary solution; I'm working on migrating to a proper database integration for the user and guild settings (for many reasons that you could probably infer).

As such, I probably wouldn't personally spend the time working on improving the filesystem approach (we have so many user issues with the filesystem approach as it is), but I do appreciate the suggestion.
