### ISSUE TITLE
How to change commandPrefix and defaultTrackedChannel on Herokus App

### ISSUE THREAD

**Issue by Kamikaze-de** [denverquane/automuteus#194]
I want to have seperate commandPrefixes for defaultTrackedChanne for external and local bot use.

Locally it is stored in the XXXXXXXX_config.json file but I can't find in the heroku App nor can I edit it.

Thank you a lot

**Comment by denverquane** [comment]
`.au settings commandprefix` and `.au settings defaulttrackedchannel`

**Comment by Kamikaze-de** [comment]
Wow far easier than I could have imagined thanks a lot!
