### ISSUE TITLE
Capture client does not support connecting to domain with .club suffix

### ISSUE THREAD

**Issue by GettingTechnicl** [denverquane/automuteus#196]
My domain ends with .club, I've been attempting to set up reverse proxy and have had issues. 

Testing has revealed that if I only put in my website for the capture client which is amongus.domainname.club I am immediately given a status code of 200. If I change this to amongus.domainname.com The bot does try to connect and times out with error. 

What is odd, is that this does work with amongus.domainname.club:8123. 

Please let me know if you need any further information from me. 

![image](https://user-images.githubusercontent.com/56567784/97376822-62fa7000-188c-11eb-9ad4-3d074cdff788.png)

**Comment by ShawnHardwick** [comment]
Based on your previous comments in other issues, you should figure out the reverse proxy issues you are having first. I highly doubt this is a TLD issue.

**Comment by INGY23** [comment]
This is a reverse proxy config issue not an issue with the .club domain, I will try and help you sort your reverse proxy in the other issue you have made
