### ISSUE TITLE
[Feature] bot using roles, instead of tags

### ISSUE THREAD

**Issue by TravisC671** [denverquane/automuteus#199]
this would be really good for easily switching the color of people in-game after they linked their account. it would also be a toggled setting. it would also be good if you could have an option to leave this on, so if my primary color was lime, I could make a carlbot reaction role and it would cooperate with the bot

**Comment by denverquane** [comment]
Hm? I really don't understand what you're asking. You mean linking the in-game "lime" character with someone who has a "lime" role in discord?

**Comment by TravisC671** [comment]
yeah
sorry for the delay, I didn't see that

**Comment by denverquane** [comment]
People change their colors a lot in-game, not to mention the game changes user's colors *for them* in the lobby. We used to use colors as the primary method of tracking which player is linked to which discord user, but using colors is not a reliable method, so I don't think we can reasonably add this feature
