### ISSUE TITLE
Docker requirements

### ISSUE THREAD

**Issue by mLgz0rn** [denverquane/automuteus#201]
What are the requirements to run it as a docker container?
I keep getting `standard_init_linux.go:211: exec user process caused "exec format error"` when I try to run it on my raspberry pi.

**Comment by denverquane** [comment]
Raspberry Pis have ARM processors, which require arm-compatible docker images. It's totally possible for this project (many users have built the underlying Go code to run on their raspberry Pis bare-metal), it's just not something that's been set up as of yet

**Comment by denverquane** [comment]
You could modify the Dockerfile to enable this functionality, it might require an ARM base image instead of the `alpine` ones that are in there now, but I don't have a lot of personal experience in building Docker images for raspberry pi
