### ISSUE TITLE
Host setting requires port even if it's standard http/https

### ISSUE THREAD

**Issue by Phoenix616** [denverquane/automuteus#214]
Currently the [host url regex](https://github.com/denverquane/automuteus/blob/4830fc3aa314acb54dc4d64c63055ca7f83f4767/discord/message_handlers.go#L18) only matches an URL if it includes a port even though that is not necessary when using standard http 80 or https 443 ports via reverse proxying.

It results in an invalid host warning when trying to link.

I think simply changing the regex to be `^http(?P<secure>s?)://(?P<host>[\w.-]+)(?::(?P<port>\d+))?/?$` (making the port group optional) could solve it.

**Comment by ShawnHardwick** [comment]
There was a discussion about this in #128.

Until this changes, put the standard port number `80` for HTTP and `443` for HTTPS if using reverse proxying.

**Comment by Phoenix616** [comment]
Yeah that's my current solution but that just doesn't look clean :S

**Comment by denverquane** [comment]
Fixed in release 4.0 :)
