### ISSUE TITLE
Latest Among Us update broke current method for scanning the game's memory

### ISSUE THREAD

**Issue by rorosaurus** [denverquane/automuteus#216]
The capture program can't find the room code anymore. I assume it's because the game recently updated with all the beta branch features, which was known to create some issues with reading the game's memory.

I assume this also breaks the monitoring of character states? I can't tell since I can't use the bot fully right now. I assume the memory has been altered to make it harder for hacked clients, so maybe this repo has a forever game of cat/mouse ahead of us? :S

**Comment by denverquane** [comment]
Huh? 2.4.2 is working perfectly on my end, and with our discord masses...
https://github.com/denverquane/amonguscapture/releases/tag/2.4.2

**Comment by rorosaurus** [comment]
Wow, this one is on me. I totally spaced out and didn't even bother to check that my exe's were up-to-date. I'm sorry for the wasted cycles on this!
