### ISSUE TITLE
Mute triggers after role sound

### ISSUE THREAD

**Issue by Coniface** [denverquane/automuteus#220]
**Problem**
I suspect this is something to sort with [amonguscapture](https://github.com/denverquane/amonguscapture) but players are muted at the end of the crewmate/impostor splashscreen.

**Current behaviour**
Player's role can leak with the sound made by the impostor's screen through the player's mic.

**Expected behaviour**
Mute should trigger at the beginning of the role screen, when role sound is about to be played.

**Comment by denverquane** [comment]
This can be changed with `.au settings delays`, and is entirely up to user preference. If you have reason to believe that most users would prefer a different delay, then submit a PR with evidence demonstrating so, but otherwise this isn't a bug, but more a subjective preference.
