### ISSUE TITLE
Unmute is a touch early at the end of games

### ISSUE THREAD

**Issue by Coniface** [denverquane/automuteus#221]
**Problem**
When the last impostor is being eliminated by the vote, all players are unmuted at the end of the elimination screen.
With the setting "Confirm Ejections" set to false, the player unmute is early and it spoils the game result.

**Current behaviour**
Players unmute happens before the victory/defeat splashscreen on last impostor's ejection vote.

**Expected behaviour**
Players unmute should happen on the victory/defeat splashscreen.

**Comment by ShawnHardwick** [comment]
Is this something that can be fixed by updating the default delay value from `DISCUSS` phase to the `LOBBY` phase? You can set this setting in the bot.
