### ISSUE TITLE
Bot only sends "blank" messages

### ISSUE THREAD

**Issue by birgersp** [denverquane/automuteus#230]
So unfortunately I seem to be only one having this problem, but the bot only sends "blank" messages to me. What's even weirder is that the Windows notification saying I got a message (from the bot) actually contains a message.

Windows notification:

![image](https://user-images.githubusercontent.com/5260237/98410399-e417eb00-2074-11eb-89ee-385b78ac87c9.png)

![image](https://user-images.githubusercontent.com/5260237/98410418-eed28000-2074-11eb-903d-61295b062808.png)

**Comment by evilangelmd** [comment]
this is due your message settings in discord.

**Comment by birgersp** [comment]
Which message settings, exactly?

**Comment by evilangelmd** [comment]
![image](https://user-images.githubusercontent.com/6436504/98536781-a4295180-2288-11eb-9693-4421a4ee2ef2.png)
Make them like this, and you will see message

**Comment by birgersp** [comment]
Great! Thanks so much!
