### ISSUE TITLE
AutoMuteUs bot randomly goes offline

### ISSUE THREAD

**Issue by TimahGelek** [denverquane/automuteus#231]
Hi first of all thanks for the bot. It has been really helpful.

The issue here is I notice the bot will sometimes go offline and is there any way I can turn it back on?

**Comment by SterlingSilber** [comment]
same here

**Comment by PaulDoesDev** [comment]
Yeah I'm seeing this too

**Comment by denverquane** [comment]
Discord was encountering large-scale DDoS attacks, as were Twitch, Youtube, Reddit, etc on 11/6 and 11/7. This should be resolved as of now, but we were seeing Discord-facing issues with receiving events and authenticating with the Discord API.
