### ISSUE TITLE
[Feature Request] Disable watching discord stream for players

### ISSUE THREAD

**Issue by nett00n** [denverquane/automuteus#234]

**Comment by denverquane** [comment]
Hm? I'm not sure I understand what you're requesting. Like not allowing fellow players to watch the discord stream of someone else still in the game? This is not possible with our bot and would fall on a Discord-level feature. I don't think there's a way to prevent someone from watching the stream of someone who is *choosing* to stream their game in Discord...

**Comment by JoshuaUndercover** [comment]
@nett00n We just ban people if they "cheat" and do that. Same as if they cheated any other way. You can disable streaming in a discord channel as a last resort too, but I hope it doesn't come to that so you guys can all play together!
