### ISSUE TITLE
User Stays Deafened After Disconnect

### ISSUE THREAD

**Issue by ShawnHardwick** [denverquane/automuteus#236]
### Expected Behavior
When a user disconnects from the game, the user should be unmuted/undeafened in Discord.

### Current Behavior
When a user disconnects from the game, the user stays unmuted/undeafened in Discord.

### Steps to Reproduce
1. During `tasks` phase, have a user disconnect.
 a. Unsure whether leaving the game qualifies for reproducing
2. Observe that the user is still muted/deafened.

### Context (Environment)
AutoMuteUs 3.1.0

### Workaround
There is no workaround, but you can get them to unmute by having them rejoin the linked Among Us lobby after the game ends.
Running `.au unmuteall` does not fix this if they are not linked.

**Comment by TheDarkLordo** [comment]
Well now the bot is definitely less aggressive, so you can unmute/undeafen players if you're the admin of the server. Anyway I agree that it's useless to leave players muted/deafed when they leave/they disconnect/they're kicked out and it's not in discussion phase

**Comment by ShawnHardwick** [comment]
Unfortunately I am not admin of the server although I do host the bot in various servers. I believe the bot should undeafen/unmute any player that disconnects during any phase but the most observed case is during tasks.

**Comment by denverquane** [comment]
Thanks for posting the issue @ShawnHardwick.

Should be fixed in the 4.0 release I'll be pushing here in a short little bit. I agree; disconnects should unmute/deafen players for sure. Might have been a regression from another update, not sure, but it should be fixed in 4.0

**Comment by ShawnHardwick** [comment]
Thanks @denverquane (and others) for your hard work on this repo. I look forward to 4.0.0. I'll close this once I can verify 4.0.0 fixes or you can close it early.
