### ISSUE TITLE
Bot does not accept IDs, roles or usernames

### ISSUE THREAD

**Issue by Wolviller111** [denverquane/automuteus#238]
The bot says that you can add users e.g. as admin using different methods, like IDs, roles or usernames. None of these three currently work however.

You will need to activate "User Intents" for your bot, so that it has access to something like user-IDs .
This was changed in October, which is why it probably worked before.

**Comment by denverquane** [comment]
True, those other methods won't work. I removed the old code as the official bot requires special whitelisting for that user intent, and I don't think it's worth it to just make the linking/adding/etc marginally easier (and in some sense, more ambiguous). 

For the time being, I'll probably change the output to not mislead and imply that these kinds of methods will work, but I'd be happy to accept a contribution to enable "self-hosted" mode or the like. If someone explicitly knows that they want to use this format, and has the User Intent enabled

**Comment by denverquane** [comment]
Added in PR https://github.com/denverquane/automuteus/pull/264
