### ISSUE TITLE
Bot messages not visible

### ISSUE THREAD

**Issue by josinjj** [denverquane/automuteus#252]
![AutoMuteUs Discord bug](https://user-images.githubusercontent.com/8620550/98898683-063dae80-2463-11eb-9187-34ee60ff3b23.JPG)
This is probably an issue with my discord settings but whenever the bot posts something, the message is not visible. I can see that it has responded in the text channel but there is no message below the Bot's name. Typing .au new yields the new private message, but again, the message is not visible.

Hopefully this is a simple discord setting.

**Comment by denverquane** [comment]
Yeah this is most likely a permissions issue. Make sure the bot has permissions to type in your channel, post embeds, etc. Most of the time I believe this is a channel permissions issue

**Comment by josinjj** [comment]
So I looked through the permissions and everything was assigned by the automatic Bot invite. This bug is also affecting the DM messages from the bot, so it is not just a server/channel permission issue.
![AutoMuteUs Discord Permissions1](https://user-images.githubusercontent.com/8620550/99611356-633be600-29c8-11eb-8c70-97523a46ba6d.JPG)
![AutoMuteUs Discord Permissions2](https://user-images.githubusercontent.com/8620550/99611357-63d47c80-29c8-11eb-8b27-1ea73c7f47fe.JPG)
![AutoMuteUs DMs also bugged](https://user-images.githubusercontent.com/8620550/99611359-63d47c80-29c8-11eb-8ce2-567b1764499d.JPG)

**Comment by denverquane** [comment]
I'm not sure what to say; I still assert my previous statement that this 100% has to be a permissions issue.

Discord did report an outage specifically relating to embeds earlier today, but I doubt that was the cause.

Are you trying `.au` commands in DMs directly to the bot? You should only be typing in channels, and those channels need to: 
1. allow the bot to post embeds and messages at the *server* level (which you're right, would be set automatically in the Bot invite link)
2. Explicitly be set per channel, both to whatever role the Bot has, but potentially to the Bot user as well. 

The bot only sends messages through standard Discord API calls; any of those calls failing (where the bot can send the message, but not Embed) can only come down to some sort of permissions issue

**Comment by josinjj** [comment]
It seems like the bot is functioning. It responds to the .au command in the text channel and also sends me the DM invite but all the messages are not visible. I just get the tag showing there is a message from the bot but there is no text after the ID tag.

Really weird. I have never seen a bug like this and use discord all the time.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by madbyte** [comment]
Have you checked your discord settings at "Text & Images"?
Maybe you have disabled some settings that are needed to show the message correctly.
![grafik](https://user-images.githubusercontent.com/5691280/99818744-e1c29000-2b4e-11eb-93c0-593fc4f883eb.png)

**Comment by josinjj** [comment]
SOLVED. It was the website preview setting.
![Bug solved](https://user-images.githubusercontent.com/8620550/99914829-ea34db00-2cb4-11eb-90b0-155f20ad00ee.png)
