### ISSUE TITLE
[Feature Request] Mute/unmute people not in the game the same as dead people

### ISSUE THREAD

**Issue by Saars1337** [denverquane/automuteus#253]
It's nice to have additional people sitting in the Discord channel so they can wait to join the game.

We find that they accidentally give away information when the discussion phase comes up without realizing

**Comment by psykzz** [comment]
Having this as a setting default to off.

**Comment by WBguy** [comment]
I think it's a great idea as people spoiling the game regularly happens to me. Sometimes they pick something up that the players don't like when someone is very quiet

**Comment by varedz** [comment]
Impossible due to rate limit issues. Would simply just be too many requests.

**Comment by RdJNL** [comment]
Well, this could be a feature for people self hosting the bot. I don't think rate limits are an issue in that case. Of course this depends on the amount of games the self hosted bot runs at the same time. But my self hosted bot runs only one game at a time, so it should be fine.

**Comment by Erfa** [comment]
This is definitely possible, SilenceAmongUs does it, although they mute spectators both during tasks and meetings. The only time spectators are allowed to speak is during the lobby phase when a game isn't ongoing. I'd really prefer if spectators followed the same rules as dead players, or at least be possible to configure.

**Comment by RdJNL** [comment]
It should be possible to configure it in the same way as you can alive and dead players.

**Comment by denverquane** [comment]
> Well, this could be a feature for people self hosting the bot. I don't think rate limits are an issue in that case.

Unfortunately not true. It's *less* of an issue, but Discord still very much limits inbound guild member PATCH requests. *Most* of the time, this is 10 mute/deafens in 10 seconds, but sometimes it dips to 5/5. Adding another worker bot is a decent mitigation, but very much not ideal for the problem.

> SilenceAmongUs does it

Sure, but as Tanner and I have discussed at length, it still introduces rate limiting and slowdowns, particularly for full games.
https://github.com/discord/discord-api-docs/issues/2204

I'm still interested in this feature to be sure, but it's not a trivial feature to implement, for several reasons

**Comment by varedz** [comment]
Beat me to it you speedy man.

**Comment by RdJNL** [comment]
Well, that sucks. I appreciate the attempt to get discord to change something to make this possible.

**Comment by denverquane** [comment]
This feature will be added very shortly, just it will just be Self-hosted/Premium only, due to how spectators impact the overall load on the bot and rate-limits :) (and it will default to "off")

I have the core functionality working on a side branch, but I might tweak if spectators are displayed in the status messages or not. It's a bit more work to determine which players are spectators, as opposed to doing all the muting behind the scenes without *any* visual display, but IMO the visual component would be nice

**Comment by RdJNL** [comment]
Awesome 👍

**Comment by denverquane** [comment]
Added in [6.8.0](https://github.com/denverquane/automuteus/releases/tag/6.8.0), will continue to work the visual component
