### ISSUE TITLE
[Feature Request] Have a second chat for the dead.

### ISSUE THREAD

**Issue by WBguy** [denverquane/automuteus#258]
Ok so this is hard to explain. feel free to contact me if you don't understand. 

My suggestion is for the bot to have a option to separate the dead and alive. I understand what I am about to request will be difficult to implement but I think It would be cool.

When this feature is on the bot makes 2 voice channels named ''Alive'' and ''Dead'' 
When someone is killed they STAY in the alive channel until discussion time and then gets moved to the ''dead'' voice channel.
This is so that the fact that people are dead is not revealed when doing tasks.
After someone gets moved to the dead channel they are unmuted and free to talk with other dead players.
Now comes the hard part. 
The idea is that the bot also joins the alive channel at the start and passes the audio from te alive channel to the dead one, so the dead people can hear the discussion. This can be done with a helper bot that gets invited to the server.

this makes it so that the dead people can talk with each other and hear the alive people, but the alive can't hear the dead. 
We have in the past manually moved the dead to a seperate channel but they obviously could not hear the alive. This alone has made it less boring when you are dead

**Comment by mikkel-ol** [comment]
You do realise that this exact thing is already present except for the dead being able to talk during discussion. The alive players are deafened and muted during rounds, so dead people can talk with each other.

**Comment by WBguy** [comment]
Thanks. I did bot realise. Sorry for the inconvenience.
