### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by cr4shed666o** [denverquane/automuteus#265]
what should I do?
![image](https://user-images.githubusercontent.com/47299921/99555733-afd7ef00-29d1-11eb-84b4-35df34938c05.png)

**Comment by ShawnHardwick** [comment]
Sounds like a networking or configuration issue. Make sure you can telnet to the address and port your specified from the computer you are running the capture program in.

**Comment by denverquane** [comment]
Closing to continue discussion here: https://github.com/denverquane/automuteus/issues/271
