### ISSUE TITLE
Cannot change the language[JP]

### ISSUE THREAD

**Issue by nanimosiranai** [denverquane/automuteus#266]
.au s language ja

I can't change it when I type.

Error Message
Language not found! Available language codes: [en de fr nl ru zu]

The version is 4.0.4.
I've also wget the following

https://raw.githubusercontent.com/denverquane/automuteus/master/locales/active.ja.toml

Please help.

**Comment by ShawnHardwick** [comment]
You can wait for the next release that will probably include JP or you can re-compile the bot.

**Comment by ShawnHardwick** [comment]
I can confirm the same.

`
2020/11/20 03:12:10 [Locale] Loaded language: de - Deutsch
2020/11/20 03:12:10 [Locale] Loaded language: en - English
2020/11/20 03:12:10 [Locale] Selected language is en 
2020/11/20 03:12:10 [Locale] Loaded language: fr - Français
2020/11/20 03:12:10 [Locale] Loaded language: nl - Nederlands
2020/11/20 03:12:10 [Locale] Loaded language: ru - Русский
2020/11/20 03:12:10 [Locale] Loaded language: zu - Engwish ᅌwᅌ`

**Comment by nanimosiranai** [comment]
Rebuilding t

> I can confirm the same running 4.0.4
> 
> ```
> 2020/11/20 03:12:10 [Locale] Loaded language: de - Deutsch
> 2020/11/20 03:12:10 [Locale] Loaded language: en - English
> 2020/11/20 03:12:10 [Locale] Selected language is en 
> 2020/11/20 03:12:10 [Locale] Loaded language: fr - Français
> 2020/11/20 03:12:10 [Locale] Loaded language: nl - Nederlands
> 2020/11/20 03:12:10 [Locale] Loaded language: ru - Русский
> 2020/11/20 03:12:10 [Locale] Loaded language: zu - Engwish ᅌwᅌ
> ```

I also rebuilt the docker environment and it was the same.

**Comment by denverquane** [comment]
The deployed bot is running the built docker image for 4.0.4, and it's been in Japanese all day with no issues...
![Capture](https://user-images.githubusercontent.com/9044037/99756971-9efbac00-2aab-11eb-84c2-be8804b28a5d.PNG)

You can see the commit is https://github.com/denverquane/automuteus/commit/e9c6210cd710ecf0a87da1a8ce30f5ae39ae6fc6,
and confirming in the K8s config, we're simply pulling the 4.0.4 image from Dockerhub, no modifications. 
![Capture](https://user-images.githubusercontent.com/9044037/99757124-fac63500-2aab-11eb-9f8d-2f87f0fcdc39.PNG)
Not sure what the issue is...

**Comment by ShawnHardwick** [comment]
![image](https://user-images.githubusercontent.com/5496527/99758447-b2b10d80-2abf-11eb-9845-f236d2462235.png)

I'm not sure either.

**Comment by nanimosiranai** [comment]
The official bot is now in Japanese.
![SnapCrab_NoName_2020-11-20_13-36-3_No-00](https://user-images.githubusercontent.com/73390827/99758558-5c7eb180-2b35-11eb-9465-96c97d80b22a.png)

In my vultr environment is the same as ShawnHardwick's
![SnapCrab_NoName_2020-11-20_13-34-49_No-00](https://user-images.githubusercontent.com/73390827/99758665-90f26d80-2b35-11eb-8b2f-0dbf36e5c0cf.png)

**Comment by denverquane** [comment]
Maybe something to do with the old `locales` volume not being removed entirely?

**Comment by ShawnHardwick** [comment]
> Maybe something to do with the old `locales` volume not being removed entirely?

That's exactly what it was. I use a non-persistent volume for my container, but I do not delete the volume in-between upgrades.

![image](https://user-images.githubusercontent.com/5496527/99760236-3b7c7900-2ac1-11eb-92d6-2a9fe6265c1c.png)

**Comment by nanimosiranai** [comment]
> Maybe something to do with the old `locales` volume not being removed entirely?

Thank you. I could too.
