### ISSUE TITLE
Add option to logs to stdout

### ISSUE THREAD

**Issue by rohannair** [denverquane/automuteus#267]
Trying to deploy this onto ECS isn't because of the log volumes needing to persist on an (effectively) ethereal VM, causing permission issues when trying to actually _open_ the `logs.txt` file to write to.

If logs are going to stdout, they will be automatically captured by the docker log agent, which will pass them to the Cloudwatch agent that comes included whenever you deploy an ECS task.
![Screen_Shot_2020-11-19_at_5 43 31_PM](https://user-images.githubusercontent.com/3764902/99737989-841f3c80-2a97-11eb-842b-ce9c812c730f.png)

**Comment by denverquane** [comment]
Try `DISABLE_LOG_FILE`=true . All logs print via stdout, but also print to a file by default

**Comment by ShawnHardwick** [comment]
Not sure if this is related to #235 where I had to set the volume permissions manually.

**Comment by rohannair** [comment]
YES totally is @ShawnHardwick. Going to close this issue and comment a bit more on #235
