### ISSUE TITLE
Discord Overlay

### ISSUE THREAD

**Issue by ryantheleach** [denverquane/automuteus#270]
Create API allowing a discord overlay to correctly position and give crewmate colors to discord members.

https://streamkit.discord.com/overlay

**Comment by denverquane** [comment]
Contributions welcome!

**Comment by CarbonNeuron** [comment]
seems like cheating.
feel free to add this yourself or by using one of the methods I posted about in the issue you made on the Capture. 

For future reference. Please don't cross post.
