### ISSUE TITLE
Add settings option for default Voice channel

### ISSUE THREAD

**Issue by redsoxfn820** [denverquane/automuteus#273]
Hello,

I may be missing how to do this, but I can see an option for default voice channel when I enter ".au settings show"

Unfortunately I don't see an option in the settings commands for changing it. It would be nice to set that so I can just start new games without having to set the track

Thanks

**Comment by denverquane** [comment]
The setting has been removed, as it invalidates the ability to have multiple games in 1 discord channel. The setting has actually been completely unfunctional for weeks now. 😄 

When you type `.au new`, if you're already in a voice channel, that channel will be used for tracking.

**Comment by redsoxfn820** [comment]
Oh perfect thanks for the clarification
