### ISSUE TITLE
WORKER_BOT_TOKENS does not respond?

### ISSUE THREAD

**Issue by nanimosiranai** [denverquane/automuteus#284]
Version up and changes were made

DISCORD_BOT_TOKEN_2=Nz...

Changed below

WORKER_BOT_TOKENS=Nz...

But there is no response.
Looking at the log, only one BOT is activated.
Am I wrong about this?

**Comment by denverquane** [comment]
The worker bots are all sent to Galactus, which is responsible for managing them. You'd see the logs in galactus

**Comment by nanimosiranai** [comment]
Thank you!
