### ISSUE TITLE
Capture not linking despite port being available

### ISSUE THREAD

**Issue by luigicrafter** [denverquane/automuteus#299]
The capture is not linking. But the port is available and reachable by Webbrowser. 
![e79c94070bb55d22b05a20ae2ad7b506](https://user-images.githubusercontent.com/39123442/100894901-45d54480-34bd-11eb-8602-57cb59f06959.png)
![a7b968c4d3b852c8623b2cc7724bdf6a](https://user-images.githubusercontent.com/39123442/100895053-6e5d3e80-34bd-11eb-915d-756cf6060a3f.png)

**Comment by folkvir** [comment]
I think this is a problem with socket io connections between the capture and galactus. A simple Javascript Socket-io client is able to connect to the socket.io server. However, the capture does not.
https://github.com/denverquane/amonguscapture/issues/104
