### ISSUE TITLE
[Help] How to change delays between phases

### ISSUE THREAD

**Issue by Asymat** [denverquane/automuteus#313]
I couldn't find how to change mute delays of different phases. Please help me or update readme.

Here what I found so far:
`.au settings delays ??????`
https://newreleases.io/project/github/denverquane/automuteus/release/v2.1.0-prerelease

**Comment by denverquane** [comment]
From the very output from the bot itself:
`.au settings delays`
```
delays
Specify the delays for automute/deafen between stages of the game, like lobby->tasks
Current Value
N/A
Example
delays lobby tasks 5
Arguments
<start phase> <end phase> <delay>
Aliases
delays, d
```

So `.au s delays lobby tasks 5` would be 5 second delay going from lobby to tasks

**Comment by Asymat** [comment]
Thanks you so much. Dunno how I missed that.

For those interested in default settings : 
```
.au s d lobby tasks 7
.au s d lobby discussion 0
.au s d tasks lobby 1
.au s d tasks discussion 0
.au s d discussion lobby 6
.au s d discussion tasks 7
```
