### ISSUE TITLE
[BUG] Uncached Users are Displayed with Discord's Internal ID

### ISSUE THREAD

**Issue by SeanGrayCS** [denverquane/automuteus#328]
On the Guild Stats and any other message post the bot makes where it @ mentions a user, if that user is uncached, their ID will be displayed instead. For example: <@!74747382818837482829> will be displayed instead of the user's username. As far as I can tell, this can be resolved by replacing userId with nick in places where the bot displays userId in a message. (Note: I haven't looked extensively at your code so this may be an incorrect/incomplete resolution).

**Comment by denverquane** [comment]
Wow, this was perfect timing. We've been discussing this on our Discord server for the past hour; yes, I think displaying the nickname or underlying username is a good option. We'd have to fetch the username/nick from Discord directly (using an API request), as the UserIDs are stored in the Database without any other naming information (foreign key reference), but it should be doable.

**Comment by denverquane** [comment]
Closing as this should be addressed in 6.7.0 with the addition of the new "leaderboardMention" setting
