### ISSUE TITLE
API Rate Limit makes people stay muted during discussion because bot(s) edit Message and trigger rate limit.

### ISSUE THREAD

**Issue by Flewrider** [denverquane/automuteus#335]
I would think that editing the bot message is lower priority so it would be preferable to buffer those edits till all players have the correct mute status.

I think this is the problem here.

**Comment by Flewrider** [comment]
Of course this would work even better in conjunction with the additional bot of the among us capture client.

**Comment by denverquane** [comment]
Editing the message is not why this occurs.

Discord's various APIs have several different endpoints which are all ratelimited individually: https://discord.com/developers/docs/topics/rate-limits 

Aka the mute/deafen endpoint (PATCH /guild/members I believe) is totally distinct from the endpoint for editing/posting/deleting messages. Discord's own API docs indicate this difference as the message deletion endpoint, for example, has a much higher ratelimit for moderation-related purposes, as opposed to other API request types.

Appreciate the suggestion, but this is not how Discord's API works. The only other ratelimit is the Global Bot ratelimit, which is probably reached by the bot on occasion, but would not explain why the message is edited but users are not muted/unmuted

**Comment by Flewrider** [comment]
What would you suggest as a solution for this problem? I'm using both yours and among us captures bot as they should work in conjunction to fix this

**Comment by denverquane** [comment]
Do you see text indicating "Successfully applied mute/deafen" or the like in your capture bot console window? If not, then the capture bot isn't being used; the official bot + capture bot is often plenty of requests in combination to be able to fully mute/unmute a whole lobby of players

**Comment by Flewrider** [comment]
No I do not see such text. You got a way to debug what could be the cause of that?

**Comment by denverquane** [comment]
Do you see "connected to Discord successfully" at the top of your capture logs? My best guess would be that initial connection or something. If a mute/deafen request from the official bot to your client bot times out, the official bot won't re-attempt using your capture bot for another 5 minutes.

**Comment by Flewrider** [comment]
Yes I do have that message but the bot is still not being used even after reconnecting it by resubmitting the api token.

**Comment by denverquane** [comment]
I'll bump up the timeout and see if that resolves it. Should redeploy a few hours from now with that change

**Comment by Flewrider** [comment]
ok will close if fixed. Also contacted amongUsCapture to see if they have an idea.

**Comment by Flewrider** [comment]
Ok i will close now. Guy from Among Us capture told me there is a list for worker bots you can provide to automuteus. Didn't know that and didn't use that. Will try tomorrow.
