### ISSUE TITLE
Bot fails when another program has log file open for amongusCapture

### ISSUE THREAD

**Issue by ericskelton** [denverquane/automuteus#336]
I wrote a python script that reads the logs of amongusCapture to mute/unmute spotify during meetings (yes I know I should be running a socket server, but I haven't really figured out how to do this yet). This works fine, but if you try to run both, the discord bot will not connect to amongusCapture. Obviously this is a pretty obscure problem but I thought I would bring it to your attention

**Comment by denverquane** [comment]
This is an obscure issue indeed. I don't think this issue really belongs in this repo for a few reasons though.

The communications between the capture and the bot are entirely over socket.io (websockets). So there's really no way that the bot specifically could fall unless you are interfering with that socket connection, or interfering with the capture's ability to process events in general (certainly possible if you happen to be blocking the log file I/O). But that's not a bot issue.

You said it yourself; reading from the log file is a hacky solution to say the least. I think there's been some work on the capture to expose a proper API for these kinds of integrations; you might want to repost this issue (with more details and/or logs+screenshots, please) on that repo instead

**Comment by ericskelton** [comment]
Thank you for the fast reply!

I don't see why it would be blocking the I/O, so yes it has got to be an issue with the capture. My goal anyway was to get it working via socket.io so hopefully that fixes things.
