### ISSUE TITLE
[Question] What permissions does the discord bot need?

### ISSUE THREAD

**Issue by RdJNL** [denverquane/automuteus#339]
I'm self hosting the bot, and I'm getting some 403 errors from the discord API (error code 50013 from discord). What permissions does the bot need in my server? Because it seems to work just fine.

**Comment by denverquane** [comment]
Is 403 a message not found error? Are you using the "autorefresh" setting? If so, that's a bug I'm still trying to resolve

**Comment by RdJNL** [comment]
Nah, 403 is not authorized. I looked up 50013 on the discord website and it means the bot is missing a permission for something it's doing. Auto refresh was off when I saw the error.

**Comment by denverquane** [comment]
Ah fair enough. You can see the full list of permissions that the bot uses here: https://add.automute.us (no need to add it if you don't like, you can simply view the permissions and then back out)

**Comment by RdJNL** [comment]
That list seems to contain a lot of permissions which seem unnecessary to me. Things like managing channels, connecting to voice channels, etc.

**Comment by denverquane** [comment]
Indeed, it's a super-set of possible and actual permissions. This is because if we added a feature in the future that necessitated higher permissions, all *19 thousand guilds* would need to reinvite the bot. Self select permissions as you deem necessary for the functionality you want, but those are the permissions for the official bot.

**Comment by RdJNL** [comment]
Makes sense. But do you have any idea which permissions are used right now?

**Comment by denverquane** [comment]
![Capture](https://user-images.githubusercontent.com/9044037/103426461-f8f59400-4b76-11eb-89e0-fa4667cf28f0.JPG)

**Comment by denverquane** [comment]
And to elaborate a bit on the crossed out permissions, these were the prospective features that would require those permissions:

* Manage Channels / Move Members: If the bot were to ever create dedicated channels for dead/alive players separately (or for creating a dedicated text channel for subsequent games... 👀 )
* Manage Nicknames: An old feature that might be revived that changes player's Discord nicknames to match their in-game names (was a pain to manage, affected ratelimits, and required specific role hierarchies to function correctly)
* Change Nickname: Would allow the bot to change its nickname in a server; purely cosmetic 
* Send TTS Messages / Connect / Speak / Use Voice Activity: If the bot were to ever "announce" games starting in voice chat or the like

Hope this helps you (and others) understand some of the permissions required :)

**Comment by RdJNL** [comment]
Yes, that's very useful, thank you. I think "manage messages" was the one I didn't have enabled. Maybe you should add this info to the readme.

And thanks for the bot, it really works amazingly.
