### ISSUE TITLE
[Feature Request] Push to talk, one user at a time

### ISSUE THREAD

**Issue by philipGaudreau** [denverquane/automuteus#376]
**Request:**

There is one option that could come handy when we play on a server with 10 people: the push to talk mechanism, but in a way that, if someone holds the mic (has the voice activity, i.e. has pushed the button to talk)), then the other players are muted, so we can actually listen to what he/she has to say, rather than having 2-4 people talking at the same time. There could be a limit of, say, 20 seconds per intervention, and there could be a queue to manage who is the next person to talk (who has pushed next to talk).

**Comment by denverquane** [comment]
As much as I appreciate the idea, this is simply not possible with the Discord API. Or, in any form that resembles what you're talking about (it would have very high latency), it would hit Discord's API rate limits, and then not be able to mute/unmute anyone for a period of time.
