### ISSUE TITLE
Stats not working with self-hosted bot

### ISSUE THREAD

**Issue by KovuTheHusky** [denverquane/automuteus#381]
All user stats show:
- Games Played: -1
- Total Wins: -1
- Winrate: -1/-1 | 0%

My guild stats show:
- Games Played: -1

Running `.au stats guild reset confirm` shows:
Encountered the following error when deleting the server's stats: ERROR: column "guild_id" does not exist (SQLSTATE 42703)

Any help would be greatly appreciated.

**Comment by denverquane** [comment]
Full logs from the bot? Sounds like it failed to create the database tables on startup.

Make sure the env variable `AUTOMUTEUS_OFFICIAL` isn't set; this prevents the bot from creating any tables

**Comment by KovuTheHusky** [comment]
Hopefully I've snipped all of the personal stuff and I'm not leaking any tokens.

Latest output from `docker-compose up`:
https://gist.github.com/KovuTheHusky/38b88a0e445d25a4742237451f8c7b90#file-latest-log

Environment variables:
https://gist.github.com/KovuTheHusky/38b88a0e445d25a4742237451f8c7b90#file-env

I can peek at the logs the next time my group plays to see if inserts/updates are failing.

Is it at all possible that column was missing in an interim version (I've been running AMU since 1.x and update pretty often) so maybe I have the table but with some columns missing?

**Comment by denverquane** [comment]
Yeah it looks like the table schema might already exist (so it's not being recreated; `create table if not exists`), but it has a different format. 

If you're upgrading from a previous v5 or lower version, it might be a good idea to delete the underlying postgres volume to let it recreate the tables from scratch; I'm seeing this error `2021-01-22 18:11:40.416 UTC [28] ERROR:  column "guild_id" does not exist` in your logs when the bot is trying to create the tables.

I think `docker volume ls` would help in identifying the postgres volume, should be something like `automuteus_postgres-data` or the like.

**Comment by KovuTheHusky** [comment]
Removed the postgres data, started AMU, seems to work (reading 0 instead of -1). Thanks, @denverquane!
