### ISSUE TITLE
Can't see continue button after inviting bot to server

### ISSUE THREAD

**Issue by joemart** [denverquane/automuteus#387]
I had a display issue where I had to open inspect on Chrome and fix the height of an element for me to click on the "Continue" button.

**Comment by Wolfhound905** [comment]
This is not out problem, it is Discord. They don't have a scroll bar. All you had to do is zoom out with crtl + -

**Comment by joemart** [comment]
I see! I solved it in a different way, but this way is much simpler! Thank you!
