### ISSUE TITLE
Opting other users out of data collection

### ISSUE THREAD

**Issue by Noctuaris** [denverquane/automuteus#388]
Hi! I'm having a weird glitch with the stat command where users who have left the discord server we play on, which kind of breaks the guild stats. Wherever these players showed up in the stats, their discord username is now replaced with their discord IDs. It kinda feels like a waste of space in the stats since these players won't show up anymore, and with the "Most Frequent First Target" stat it is not possible to have them disappear after a good amount of games since this precise stat is ordered by percentage and not count. If possible, the option to opt other players out with admin privileges would be nice, but an automatic check for users who are no longer present on the server would be even nicer. I don't know what's possible and what's not but it feels like there should be a way to erase the data collected from players who are no longer playing on a server.

Thanks, everyone for the hard work!

Ps: I have attached a screenshot of what I'm referring to.
![Screenshot_525](https://user-images.githubusercontent.com/20501480/106319549-e5bb0e80-6271-11eb-8e40-7e45c66ee287.png)

**Comment by denverquane** [comment]
Sure, you can use `.au stats @player reset` to clear the data for that player. In this context, copying that mention directly (`<@1234...>`) should do the trick

**Comment by Noctuaris** [comment]
Oh great ! I had not seen this ! Thanks a bunch for the tip !
