### ISSUE TITLE
After 1st discussion, the app looks hung up.

### ISSUE THREAD

**Issue by snmatsui** [denverquane/automuteus#389]
app version 3.1.2

After 1st disucussion, the state of among us capture was still DISCUSSION, discord voice states were unmuted and speaker unmuted in spite of the game state was not discussion. 

The log of among us capture has these exceptions.
```
{
  "guildID": ****,
  "userID": ****,
  "parameters": {
    "deaf": true,
    "mute": true
  },
  "taskID": "****"
}Status: RanToCompletion, Exception: , Faulted: False
```

and 

```
System.NullReferenceException: Arg_NullReferenceException
   at AmongUsCapture.GameMemReader.RunLoop()
```

This case was reproduced through every 4 games.

**Comment by denverquane** [comment]
This should be fixed in capture version 3.1.3, please try upgrading to that version. This issue belongs in that repository anyways

**Comment by snmatsui** [comment]
No troubles occured Until a few days ago.
I updated among us capture today (probabry from 6.10.1)
However, my windows environment may be changed yesterday. after installing other software, communicating between apps may have trouble like discord app cannot capture another app sound.

**Comment by snmatsui** [comment]
Thank you.

**Comment by snmatsui** [comment]
I mistook the repository.
I am sorry for opening issue about among us capture.

**Comment by denverquane** [comment]
No problem! :)
