### ISSUE TITLE
Proximity Mode

### ISSUE THREAD

**Issue by zeeem** [denverquane/automuteus#395]
is there any way we can use it for proximity chat?

I guess [auProximity](https://github.com/cybershard/auproximity) does a similar thing but requires users to keep the browser open in the background (which is not always possible for mobile players).

**Comment by denverquane** [comment]
There is not.

Discord's API is not extensible enough to make this easily possible, either. Open to suggestions, but Discord bots cannot adjust player volumes, and it would require multiple voice channels, etc.

**Comment by zeeem** [comment]
Ohh I see.

https://github.com/Frazew/CrewComms 
I guess they are trying to achieve this., not sure if it's released yet or not.

**Comment by Wolfhound905** [comment]
For sure do not think they are going to be able to make it cross-platform, if they actually want to make a prox mod that is for discord there would need to be a discord plugin that can adjust the volume of users' client-side. That is the only way I see a prox mod for among us in discord. 👀

**Comment by Wolfhound905** [comment]
It seems their project has died 😕

**Comment by zeeem** [comment]
Yeah.. :(
