### ISSUE TITLE
[Feature request] Link cache

### ISSUE THREAD

**Issue by darkomtc11** [denverquane/automuteus#82]
Hey,

maybe this isn't possible to do, since I don't know if players have unique IDs.
But if you can extract some sort of player ID (persistent, doesn't change even after restart), you can cache the link between Discord @username and that ID, binary file for example. On capture start, player connect, or lobby join, it can try to link players automatically.

**Comment by darkomtc11** [comment]
To simplify the process of linking (again, if possible), it can only link if the given player from cache is currently connected to selected voice channel and also has joined the lobby. If both conditions are true, the link can happen. I'm saying "only selected voice channel" because I wouldn't like a link to happen if the player is only inside lobby (not connected to any or connected to other channels unrelated to Among Us). If no channel is selected to be primary channel for Among Us bot, any channel join should trigger link.

![among_us_auto_link](https://user-images.githubusercontent.com/45644502/94804073-87c50a00-03ea-11eb-9019-f8412f47fd81.png)

I would have made the pull request, but I don't know Go. 😅

**Comment by denverquane** [comment]
Added in 2.4.0 release :)
